stripe.secretKey=sk_test_51QuBaRK6dhIc7YOm3TJxxTw409Wxuzkk6Mis7LVPEuitjglkIn3zChdiE6jweMVW7Mn4Na8WCTLJPymFvbL7mh4v00azltuaWj


spring.application.name=resumeBuilder
spring.jpa.hibernate.ddl-auto=update
# this run on server
# spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/resume_builder
# spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5434/resume_builder
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/resumes
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.error.whitelabel.enabled=true
# https://www.baeldung.com/spring-boot-controllers-add-prefix
# server.servlet.contextPath=/api

# springdoc.api-docs.path=/api-docs


spring.security.user.name=tungbe
spring.security.user.password=1234567
logging.level.org.springframework.security=DEBUG

# jwt
# JWT Configuration

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

logging.level.org.springframework.http.converter.json=DEBUG

spring.servlet.multipart.enabled=true
#default = 1MB
spring.servlet.multipart.max-file-size=50MB  


#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB


STRIPE_Publishable_KEY = pk_test_51QuBaRK6dhIc7YOm8t5bQlthKmgJO3J5xNrYqUebCHfPJhwTOoqgc6z3XPOZ7xMxbGlJjyeutPMGBfDK23A1CBIk00Lb1l4JrJ
STRIPE_SECRET_KEY = "sk_test_51QuBaRK6dhIc7YOm3TJxxTw409Wxuzkk6Mis7LVPEuitjglkIn3zChdiE6jweMVW7Mn4Na8WCTLJPymFvbL7mh4v00azltuaWj"


STRIPE_BASIC_MONTHLY ="price_1RDs8aK6dhIc7YOmzDcI2XMV"
STRIPE_PREMIUM_MONTHLY = "price_1RDsAFK6dhIc7YOmRMlGQFxw"
CARD=4242 4242 4242 4242

STRIPE_WEBHOOK_SECRET = "whsec_fVqd42xr6WDkutkorecqZMsHwJtBcZXU"

# OPENAI_API_KEY=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
OPENAI_API_KEY=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


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dothedung131@gmail.com
spring.mail.password=aqzq gstl dhti pyzt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=noreply@example.com



spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest